# [options]
# admin_passwd =aeboisSecured@
# db_host = False
# db_port = False
# db_user = odoo
# list_db = True
# db_password = aebo_code_db_p@ss
# addons_path = /home/ubuntu/Aebo_webapp/addons,/home/ubuntu/Aebo_webapp/custom_addons
# xmlrpc_interface = 0.0.0.0
# xmlrpc_port = 8070
# logfile = /var/log/odoo18.log
# proxy_mode = True
# wkhtmltopdf_path = /usr/bin/wkhtmltopdf

[options]
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo
db_password = AeboCODE@777
addons_path = C:\Odoo_18\Odoo_18\odoo\addons
default_productivity_apps = True